name: spendsmart
description: "AI Powered Budgeting App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  carousel_slider: ^5.1.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  ionicons: ^0.2.2
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/onboarding/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true
  image_path: "assets/icons/app_logo.png"
  adaptive_icon_foreground: "assets/icons/app_logo.png"

flutter_native_splash:
  android: true
  ios: true
  web: true

  color: "#ffffff"
  image: "assets/icons/app_logo_nobg.png"

  android_12:
    color: "#ffffff"
    image: "assets/icons/app_logo_nobg.png"
